config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :establishments, except: :index do
    resources :reviews, only: %i[new create]
  end

  # resources :review_tags, only: [:create, :new] do
  # end

  resources :establishments, only: :index do
    member do
      post 'toggle', to: "favorites#toggle"
    end
  end

  resources :users do
    resources :favorites
  end

  get 'toggle_map', to: "pages#toggle_map", as: "toggle_map"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>The dogs that inspired us ♥️ </p>
  <a href="https://www.instagram.com/tacomeetsworld/" target="_blank">
    <i class="fab fa-instagram"></i> Taco
  </a>
  <a href="https://www.instagram.com/looneylunathesamoyed/?igshid=OGQ2MjdiOTE%3D" target="_blank">
    <i class="fab fa-instagram"></i> Luna
  </a>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar">
  <%# Logo %>
  <%= link_to root_path do %>
    <%= image_tag "bbf.png", class: "logo" %>
  <% end %>

  <%# Easter Egg %>
  <%= image_tag "rainbow_wizard.gif", class: "wizard" %>

  <%# Log-in Dropdown bar %>
  <% if user_signed_in? %>
    <ul class="flex items-center justify-end">
      <%= render 'shared/navbar_dropdown' %>
    </ul>
  <% else %>
    <li >
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    </li>
  <% end %>

  <%# Greeting message %>
  <% if request.path == root_path %>
    <div class="banner">
      <% if current_user.present? && (request.path == root_path || (@establishment.try(:path) == request.path)) && !request.path.include?("favorites") && !request.path.include?("new") %>
        <% current_hour = Time.now.hour %>
          <% if current_hour < 12 %>
            <h1>Good morning, <%= @user.username %>!</h1>
          <% elsif current_hour < 17 %>
            <h1>Good afternoon, <%= @user.username %>!</h1>
          <% else %>
            <h1>Good evening, <%= @user.username %>!</h1>
          <% end %>
      <% end %>
    </div>
  <% end %>

  <%# Filters Group %>
  <% if request.path == root_path %>
    <div style="width: 100%;">
      <%= turbo_frame_tag 'turbo-list', data: { turbo_action: 'advance' } do %>
        <div class="container-icons icon-background">

          <%= link_to root_path(location_type: "cafe") do %>
            <div class="icon" >
              <i class="fa-solid fa-mug-saucer <%= 'active_tab' if @cafe_active %>"></i>
              <p class="<%= 'active_tab' if @cafe_active %>">Cafe</p>
            </div>
          <% end %>

          <%= link_to root_path(location_type: "bar") do %>
            <div class="icon">
              <i class="fa-solid fa-wine-glass <%= 'active_tab' if @bar_active %>"></i>
              <p class="<%= 'active_tab' if @bar_active %>">Bars</p>
            </div>
          <% end %>

          <%= link_to root_path(location_type: "beach") do %>
            <div class="icon">
              <i class="fa-solid fa-umbrella-beach <%= 'active_tab' if @beach_active %>"></i>
              <p class="<%= 'active_tab' if @beach_active %>">Beaches</p>
            </div>
          <% end %>

          <%= link_to root_path(location_type: "trail") do %>
            <div class="icon">
              <i class="fa-solid fa-person-hiking <%= 'active_tab' if @trail_active %>"></i>
              <p class="<%= 'active_tab' if @trail_active %>">Trails</p>
            </div>
          <% end %>

          <%= link_to root_path(location_type: "park") do %>
            <div class="icon">
              <i class="fa-solid fa-tree <%= 'active_tab' if @park_active %>"></i>
              <p class="<%= 'active_tab' if @park_active %>">Parks</p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar_dropdown.html.erb
<div data-controller="dropdown" class="relative inline-block">
  <button type="button" data-action="dropdown#toggle click@window->dropdown#hide"><i style = "font-size: 24px;" class="fa-solid fa-bars"></i></button>
  <div
    data-dropdown-target="menu"
    class="absolute right-0 z-10 mt-2 w-44 origin-top-right rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
    data-transition-enter-from="opacity-0 scale-95"
    data-transition-enter-to="opacity-100 scale-100"
    data-transition-leave-from="opacity-100 scale-100"
    data-transition-leave-to="opacity-0 scale-95"
    >
    <div class="py-1">
      <%= link_to user_favorites_path(current_user), data: {action: "dropdown#toggle"}, class: 'text-black group flex items-center px-4 py-3 hover:bg-gray-100 hover:text-gray-900 rounded-none m-0' do %>
        <%= image_tag "bbf3.png", class: "icon mr-2 w-1.7rem h-1.7rme" %>
        <span class="text-sm">Favourites</span>
      <% end %>
      <%= link_to new_establishment_path, data: {action: "dropdown#toggle"}, class: 'text-black group flex items-center px-4 py-3 hover:bg-gray-100 hover:text-gray-900 rounded-none m-0' do %>
        <i class="fa-solid fa-circle-plus mr-2 h-6 w-6"></i>
        <span class="text-sm">New Location</span>
      <% end %>
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete, action: "dropdown#toggle"}, class: 'text-black group flex items-center px-4 py-3 hover:bg-gray-100 hover:text-gray-900 rounded-none m-0' do %>
        <i class="fa-solid fa-arrow-right-from-bracket mr-2 h-6 w-6"></i>
        <span class="text-sm">Logout</span>
      <% end %>
    </div>
  </div>
</div>