config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :establishments, except: :index do
    resources :reviews, only: %i[new create]
  end

  # resources :review_tags, only: [:create, :new] do
  # end

  resources :establishments, only: :index do
    member do
      post 'toggle', to: "favorites#toggle"
    end
  end

  resources :users do
    resources :favorites
  end

  get 'toggle_map', to: "pages#toggle_map", as: "toggle_map"
end

app/views/pages/_info_window.html.erb
<%= link_to establishment_path(establishment) do %>
    <h2><%= establishment.name %></h2>
    <p><%= establishment.address %></p>
<% end %>

app/views/pages/home.html.erb
<div class="container">
  <div>
    <% case params[:location_type] %>
      <% when "bar" %>
        <strong><p>All Dog-friendly Bars</p></strong>
      <% when "beach" %>
        <strong><p>All Dog-friendly Beaches</p></strong>
      <% when "trail" %>
        <strong><p>All Dog-friendly Trails</p></strong>
      <% when "park" %>
        <strong><p>All Dog-friendly Parks</p></strong>
      <% else %>
        <strong><p>All Dog-friendly Cafes</p></strong>
      <% end %>
  </div>
    <div class="change-display">
      <% if session[:show_map] %>
        <%= link_to toggle_map_path do %>
          Show list <i class="fa-solid fa-list"></i>
        <% end %>
      <% else %>
        <%= link_to toggle_map_path do %>
          Show map <i class="fa-solid fa-map"></i>
        <% end %>
      <% end %>
  </div>
  <% if session[:show_map] %>

    <div data-controller="map"
        id="map"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style="width: 100%; height: 400px;">
    </div>

  <% else %>

    <div class="container">
      <div class="row">
        <% @establishments.each do |establishment| %>
          <div class="col d-flex justify-content-center my-3">
            <div class="card-fav">
                <div class="fav-btn hp">
                  <% if current_user.present? %>
                      <%= turbo_frame_tag dom_id(establishment, :favourite) do %>
                        <% if current_user.favorited?(establishment) %>
                              <%= button_to toggle_establishment_path(establishment), method: :post, style: "border:0; background-color:transparent" do %>
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#7A23EB" style="width: 46px; height: 32px; color: #7A23EB; margin-top: 4px;">
                                <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
                                </svg>
                              <% end %>
                            <% else %>
                              <%= button_to toggle_establishment_path(establishment), method: :post, style: "border:0; background-color:transparent" do %>
                                <svg xmlns="http://www.w3.org/2000/svg" fill="transparent" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 46px; height: 32px; color: white; margin-top: 4px;">
                                  <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                                </svg>
                              <% end %>
                        <% end %>
                      <% end %>
                  <% end %>
                </div>
                <div class="row d-flex flex-column">
                  <div class="col">
                <%= link_to establishment_path(establishment) do %>
                  <div class="card-trip">
                    <img src="<%= establishment.image %>">
                    <div class="card-product-infos">
                      <div>
                        <h2> <%= establishment.name %> </h2>
                        <p style = "color: #934DE8;"><em><%= establishment.location_type.capitalize %></em></p>
                      </div>
                      <div class= "rating-icon">
                        <% for i in 1..establishment.rating %>
                          <i class="fas fa-star fa-2x text-warning m-3"></i>
                        <% end %>
                        </div>
                  </div>
                    </div>
                  </div>
                </div>
              <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>
</div>