config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :establishments, except: :index do
    resources :reviews, only: %i[new create]
  end

  # resources :review_tags, only: [:create, :new] do
  # end

  resources :establishments, only: :index do
    member do
      post 'toggle', to: "favorites#toggle"
    end
  end

  resources :users do
    resources :favorites
  end

  get 'toggle_map', to: "pages#toggle_map", as: "toggle_map"
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  validates :address, :phone, :name, :location_type, presence: true
  validates :phone, :name, :address, uniqueness: true
  validates :phone, length: { in: 8..14}
  validates :name, length: { minimum: 1 }
  validates :phone, format: {
    with: /\A(\+?\(61\)|\(\+?61\)|\+?61|\(0[1-9]\)|0[1-9])?( ?-?[0-9]){7,9}\z/,
    message: "Only allows Australian numbers"
  }
  self.inheritance_column = :_type_disabled

  has_many :reviews, dependent: :destroy
  acts_as_favoritable
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  enum location_type: { cafe: 0, bar: 1, beach: 2, park: 3, trail: 4 }

end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :set_establishment, only: %i[show edit update destroy]
  # skip_before_action :authenticate_user!, only: [:show]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @user = current_user
    @establishments = Establishment.all
    @reviews = Reviews.all
    @establishments = policy_scope(Establishment).all
  end

  def show
    authorize @establishment
    @user = current_user
    @establishment = Establishment.find(params[:id])
      @tag_count = [
        { name: "Outdoor", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Outdoor").id }).count},
        { name: "Water Bowl", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Water Bowl").id }).count },
        { name: "Indoor", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Indoor").id }).count },
        { name: "Treats", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Treats").id }).count },
        { name: "Waste Bags", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Waste Bags").id }).count },
        { name: "Dog Menu", count: @establishment.reviews.joins(:review_tags).where(review_tags: { tag_id: Tag.find_by_name("Dog Menu").id }).count }
      ]
      @tag_count = @tag_count.select { |tag| tag[:count] > 0 }
  end

  def new
    @user = current_user
    @establishment = Establishment.new
    authorize @establishment
  end

  def create
    @establishment = Establishment.new(establishment_params)
    # establishment.rating = 1 if establishment.rating.empty?
    authorize @establishment
    if @establishment.save!
      redirect_to establishment_path(@establishment)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    authorize @establishment
  end

  def update
    if current_user.present?
      authorize @establishment
      @establishment.update(establishment_params)
      if @establishment.update(establishment_params)
        redirect_to establishment_path(@establishment)
      else
        render :edit, status: :unprocessable_entity
      end
    else
     redirect_to root_path
    end
  end

  def destroy
    authorize @establishment
    @establishment.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_establishment
    @establishment = Establishment.find(params[:id])
  end

  def establishment_params
    params.require(:establishment).permit(:name, :phone, :address, :location_type, :rating, :image)
  end
end

app/views/establishments/_edit_form.html.erb
<div class="container">
    <%= form_with model: @establishment do |f| %>
      <div class="mb-3">
        <%= f.label :name, {class: 'form-label'} %>
        <%= f.text_field :name, {class: 'form-control'} %>
      </div>
      <div class="mb-3">
        <%= f.label :address, {class: 'form-label'} %>
        <%= f.text_field :address, {class: 'form-control'} %>
      </div>
      <div class="mb-3">
        <%= f.label :rating, {class: 'form-label'} %>
        <%= f.number_field :rating, {class: 'form-control'} %>
      </div>
      <div class="mb-3">
        <%= f.label :phone, {class: 'form-label'} %>
        <%= f.number_field :phone, {class: 'form-control'} %>
      </div>
      <div class="mb-3">
        <%= f.label :location_type, "Location-type", {class: 'form-label'} %>
        <%= f.collection_select :location_type, Establishment.location_types.keys, :to_s, :to_s, prompt: "Select a type" %>
      </div>
      <div class="mb-3">
        <%= f.label :image, {class: 'form-label'} %>
        <%= f.text_field :image, {class: 'form-control'} %>
      </div>
        <%= f.submit "Submit" %>
      </div>
    <% end %>
 </div>

app/views/establishments/_new_form.html.erb
<div class="container">
  <%= form_with model: @establishment do |f| %>
    <div class="mb-3">
      <%= f.label :name, {class: 'form-label'} %>
      <%= f.text_field :name, {class: 'form-control'} %>
    </div>
    <div class="mb-3">
      <%= f.label :address, {class: 'form-label'} %>
      <%= f.text_field :address, {class: 'form-control'} %>

    </div>
    <div class="mb-3">
      <%= f.label :rating, {class: 'form-label'} %>
      <%= f.number_field :rating, {class: 'form-control'} %>
    </div>
    <div class="mb-3">
      <%= f.label :phone, {class: 'form-label'} %>
      <%= f.number_field :phone, {class: 'form-control'} %>
    </div>
    <div class="mb-3">
      <%= f.label :location_type, "Location-type", {class: 'form-label'} %>
      <%= f.collection_select :location_type, Establishment.location_types.keys, :to_s, :to_s, prompt: "Select a type" %>
    </div>
    <div class="mb-3">
      <%= f.label :image, {class: 'form-label'} %>
      <%= f.text_field :image, {class: 'form-control'} %>
    </div>
      <%= f.submit "Submit" %>
    </div>
  <% end %>
</div>

app/views/establishments/_searchbar.html.erb
# <div class="container">
# <form novalidate="novalidate" class="simple_form search" action="#" accept-charset="UTF-8" method="get">
# <div class="search-form-control form-group">
# <!--
#   # <input class="form-control string required" type="text" name="search[query]" id="search_query" />
#   # <input
#   #   name="address" placeholder="Address" type="text"
#   #   autocomplete="address-line1"
#   # />
#   # <button name="button" type="submit" class="btn btn-flat">
#   #   <i class="fas fa-search"></i> Search
#   # </button>
# -->

# <div data-controller="map"
#   id="map"
#   data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
#   data-map-markers-value="<%= @markers.to_json %>"
#   style="width: 100%; height: 400px;">
# </div>


# <div style="width: 100%; height: 600px;"
#   data-controller="map"
#   id='map'
#   data-map-api-key-value='<%= ENV['MAPBOX_API_KEY'] %>' >
# </div>

# </div>
# </form>
# </div>

# display: flex;
# flex-direction: column;
# width: 100%;
# height: fit-content;

display: flex;
flex-direction: column;
width: 100%;
height: auto;

app/views/establishments/edit.html.erb
<div class="container">
  <h1>Edit your dog-friendly location below</h1>
</div>

<div class="container container-topline">
  <%= render 'edit_form' %>
</div>

<div class="icon">
      <%= button_to "Return" , root_path, :class => "btn btn-secondary",  :method => :get %>
</div>

app/views/establishments/new.html.erb
<div class="container">
  <h1>Submit your dog-friendly location!</h1>
  <h5>Type the name of your dog-friendly location below</h5>
</div>

<div class="container container-topline">
  <%= render 'new_form' %>
</div>

app/views/establishments/show.html.erb
<div class="container">
  <div class="card-trip", style="width: 350px;">
    <div style="display: flex; justify-content:space-between;">
      <h1 style='font-size: 1.6rem; font-weight: bold;'><%= @establishment.name %></h1>
      <div data-controller="dropdown"
        style="display: flex;
        justify-content: end;
        padding-right: 5px;
        z-index: 5;"
        >
        <button type='button' data-action="dropdown#toggle click@window->dropdown#hide"><i class="fa-solid fa-ellipsis-h"></i>
        </button>
        <div data-dropdown-target="menu"
          data-transition-enter-from="opacity-0 scale-95"
          data-transition-enter-to="opacity-100 scale-100"
          data-transition-leave-from="opacity-100 scale-100"
          data-transition-leave-to="opacity-0 scale-95">
          <div>
            <% if current_user.present? && current_user.admin? then policy(@establishment).edit? %>
              <%= link_to edit_establishment_path(@establishment), data: {action: "dropdown#toggle"}, method: :get do %>
                <i class="fa-solid fa-pen-to-square"></i><span style="padding-left: 5px; font-size: 0.7rem">Edit</span>
              <% end %>
            <% end %>
            <% if current_user.try(:admin?) && policy(@establishment).destroy? %>
              <%= link_to establishment_path(@establishment), data: {action: "dropdown#toggle", turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-solid fa-trash"></i><span style="padding-left: 5px; font-size: 0.7rem">Delete</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>


  <div class="card">
    <div class="container-icon">
      <img src="<%= @establishment.image %>">
      <div class="fav-btn show">
        <% if current_user.present? %>
          <%= turbo_frame_tag dom_id(@establishment, :favourite) do %>
            <% if current_user.favorited?(@establishment) %>
              <%= button_to toggle_establishment_path(@establishment), method: :post, style: "border:0; background-color:transparent" do %>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#7A23EB" style="width: 46px; height: 32px; color: #7A23EB; margin-top: 4px;">
                  <path d="M11.645 20.91l-.007-.003-.022-.012a15.247 15.247 0 01-.383-.218 25.18 25.18 0 01-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0112 5.052 5.5 5.5 0 0116.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 01-4.244 3.17 15.247 15.247 0 01-.383.219l-.022.012-.007.004-.003.001a.752.752 0 01-.704 0l-.003-.001z" />
                </svg>
              <% end %>
            <% else %>
              <%= button_to toggle_establishment_path(@establishment), method: :post, style: "border:0; background-color:transparent" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="transparent" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" style="width: 46px; height: 32px; color: white; margin-top: 4px;">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                </svg>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <div class="text-start my-2 text-muted">
        <p style="color: #7A23EB; font-family: Comfortaa, cursive;"><em><%= @establishment.location_type.capitalize %></em></p>
      </div>
      <div class="text-start">
        <p><%= @establishment.address %></p>
        <p style="font-size: 0.9rem"><%= @establishment.phone %></p>
      </div>
    </div>
      <div class="container-icons">
        <div>
          <%= button_to "tel:#{@establishment.phone}", class: 'font-icons', method: :get do %>
            <i class="fa-solid fa-phone", style="color: #7A23EB"></i>
          <% end %>
        </div>
        <div>
          <%# <%= link_to "<i class='fa-solid fa-location-arrow'></i>",target: "_blank", class: "font-icons" %>
          <%= link_to content_tag(:i, '', class: "fa-solid fa-location-arrow"), "https://www.google.com/maps?saddr=My+Location&daddr=#{@establishment.address}", class: "font-icons" , id: 'nav-button', target: "_blank", data: {location_name: @establishment.name} %>
        </div>
      </div>
    </div>
</div>

<div class="container" style="margin-bottom: 17px;">
  <div class="tag-container">
    <div class="card-trip", style="width: 350px;">
        <%# Reviews %>
      <div class="tag-container">
        <div class="d-flex justify-content-between align-items-center">
          <p style="font-size: 16px;">People often mention:</p>
          <%= button_to 'Leave a Review', new_establishment_review_path(@establishment), class: 'review-button', method: :get %>
        </div>
        <div class="tag-container">
          <% @tag_count.each do |tag| %>
            <div class="count">
              <%= "#{tag[:name]}" %><i class="tag-count ml-2"> <%= "#{tag[:count]}" %> </i>
            </div>
          <% end %>
        </div>
        <div>
          <% if @establishment.reviews.count == 0 %>
            <p>Help your fellow BBFs, be the first to leave a review on this list!</p>
          <% else %>
            <% @establishment.reviews.each do |review| %>
              <% unless review.comments == "" then %>
                <div class="card-review">
                  <h6><strong><%= review.user.username %>:</strong></h6>
                  <p><%= review.comments %></p>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/establishments/toggle_favorite.js.erb
var establishmentId = '<%= @establishment.id%>'
function toggleLikeButton(establishmentId, innerHTML) {
  let likeButton = document.querySelector(`.like-icon[data-id='${establishmentId}']`)
  likeButton.classList.toggle('red');
}
toggleLikeButton(establishmentId);